repos:
-   repo: https://github.com/myint/autoflake.git
    rev: v1.4
    hooks:
    -   id: autoflake
        args: ["--in-place", "--remove-all-unused-imports", "--ignore-init-module-imports"]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]